# Generated by Django 3.0.7 on 2021-12-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211201_2143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
